requires 'App::Prove';
requires 'Data::SSHPubkey';
requires 'Data::UUID';
requires 'File::Spec';
requires 'File::Temp';
requires 'FindBin';
requires 'Getopt::Long';
requires 'Mojo::SQLite';
requires 'Scalar::Util';
requires 'Socket';
requires 'Test::Cmd';
requires 'Test::More', '>= 0.88';
requires 'Test::UnixExit';
requires 'Text::ParseWords';
