#!/bin/sh
#
# update-ssh-hostkeys - get the SSH public keys into a known location
# that clients can download

TFILE=`mktemp -p /var/www/html ssh_known_hosts.XXXXXXXXXX` || exit 1
trap 'rm -- "$TFILE"' INT TERM HUP USR1 USR2

# TODO stat(1) the existing file (if any) and pass that to avoid
# updating the file when there is nothing new in the database
irulan ssh_known_hosts > "$TFILE" || { rm -- "$TFILE"; exit 1; }

# don't clobber (possibly good) data with a zero-sized file (the
# security team of a small internet retailer once clobbered a bunch of
# /etc/passwd files in such a fashion, hence this check...)
[ -s "$TFILE" ] && {
   chmod -- 0644 "$TFILE"
   mv -f -- "$TFILE" /var/www/html/ssh_known_hosts || exit 1

   # this server can use these ssh host keys directly (handy if you do
   # Ansible deploys from that host...)
   cp -p /var/www/html/ssh_known_hosts /etc/ssh/ssh_known_hosts
   exit $?
}

echo >&2 'warning: zero-sized ssh_known_hosts temporary file??'
exit 1
